### ISSUE TITLE
Source code for tsplib

### ISSUE THREAD

**Issue by matthieu637** [AhmedStohy/Hybrid-Pointer-Networks#1]
Hello, would it be possible to access the code for tsplib?

I'm also wondering how you dealed with data that are not represented with xy-coordinate like brazil58.tsp?

**Comment by AhmedStohy** [comment]
I uploaded it with the material that tackles large instances. You're going to find it under the large folder, then open hpnlarge-test.ipynb. Scroll down to the section "Data Preprocessing For Benchmark Instances".
Unfortunately, we only tackled data with XY coordinates. Because in the first place, we trained our model with XY-coordinated data, but we ignored any data that included a distance matrix.

**Comment by matthieu637** [comment]
I see, thank you!
